feat: 해당 달에 일기가 존재하는 날짜 조회 기능 구현
Konkuk-ThanksD/Server pull request #10
Opened 2023-10-29 09:19 UTC by Ji-soo708

## 개요
- ThanksD 서비스에는 일기를 편리하게 조회할 수 있는 달력이 존재합니다. 그렇기에 달력에 일기가 존재하는 날짜를 조회할 수 있도록 해당 기능을 구현했습니다.

## 작업사항
- Diary에 extends BaseTime 추가
- BaseTime 타입을 TimeStamp에서 LocalDateTime으로 변경
- 해당 달에 일기가 존재하는 날짜 조회 기능 로직 구현
- 관련 테스트 코드 추가 

## 주의사항
- BaseTime 타입을 LocalDateTime으로 변경했습니다
- `createdTime`은 다이어리 생성 날짜를 기준으로 설정됩니다. 그렇기에 해당 기능 관련 테스트 코드에서 year와 month를 now를 기준으로 설정하도록 했습니다
  - 이렇게 테스트 코드를 작성하면 23:59에서 x월 1일 00:00으로 넘어갈 때 ci 테스트를 수행할 경우, 일기 작성 month와 now의 month가 달라져서 ci가 실패할 가능성이 있다고 생각합니다. 하지만 이럴 가능성은 매우 희박하다고 생각하여 일단 이렇게 작성했습니다
  - 더 좋은 방법이 있다면 알려주세요

2023-10-29 09:23 UTC, Ji-soo708 commented on src/main/java/com/thanksd/server/domain/BaseTime.java
> +    private LocalDateTime createdTime;
해당 달에 일기가 존재하는 날짜 조회 기능에서는 응답 타입을 `List<LocalDate>`로 주고 있습니다.
`Timestamp`로 생성 날짜를 저장하면 Timestamp -> LocalDateTime -> LocalDate로 변환을 거쳐야 합니다.
하지만 `LocalDateTime`으로 생성 날짜를 저장하면 LocalDateTime -> LocalDate로 바로 변환을 거치면 됩니다.

그렇기에 `Timestamp`로 굳이 저장할 필요는 없어서 `LocalDateTime`으로 변경했습니다.

2023-10-29 12:31 UTC, 0703kyj requested changes
일기 pr 합쳐진지 얼마 안됐는데 엄청 빠르게 하셨네요..! 감탄하고 갑니다ㅎㅎ 고생하셨어요!😄 달력에 일기 쓴 날짜 표시하는 기능은 완벽한 것 같습니다! 그런데 해당 날짜를 클릭했을 때 날짜 별 일기를 불러오는 기능에 대해 이야기 해봐야 할 것 같아서 리뷰 남깁니다..!!

2023-10-29 12:31 UTC, 0703kyj commented on src/main/java/com/thanksd/server/service/DiaryService.java
> +                .collect(Collectors.toList());
혹시 날짜랑 해당 날짜 별로 다이어리 id를 같이 반환하는 식으로 작성하는 건 어떤가요? 날짜를 클릭하면 일기를 불러와야 할텐데 현재는 일기 id로만 불러올 수 있어서요! 아니면 날짜에 따라 일기를 다시 찾는 api를 추가할까요?

2023-10-29 12:31 UTC, 0703kyj commented on src/test/java/com/thanksd/server/service/DiaryServiceTest.java
> +        DiaryDateResponse findDiary = diaryService.findExistingDiaryDate(member.getId(), LocalDate.now().getYear(),
제가 테스트 코드를 작성했을 때, findDiary를 찾은 Diary에 대한 변수명으로 활용했어서 다른 변수명이 나중에 헷갈릴 여지가 조금 줄어들 것 같아요..!

2023-10-29 12:31 UTC, 0703kyj commented on src/test/java/com/thanksd/server/service/DiaryServiceTest.java
> +    }
말씀해주신 우려사항에 대해서 혹시 now()를 활용하지 않고 고정된 날짜로 테스트하는 건 어떤가요? 실제 서비스 할 때는 저장 시점과 달력 호출 시점은 큰 연관 없는 것 같아서요! 특정 날짜에 대해서 잘 불러온다면 문제 없을 거라 생각합니다~~

2023-10-29 12:31 UTC, 0703kyj commented on src/main/java/com/thanksd/server/service/DiaryService.java
> +                .collect(Collectors.toList());
그리고 스트림 사용하는 부분은 메서드로 빼는게 한번에 이해하기 편할 것 같아요!

2023-10-29 12:31 UTC, 0703kyj commented on src/main/java/com/thanksd/server/domain/BaseTime.java
> +    private LocalDateTime createdTime;
네 확인했습니다!

2023-10-29 12:42 UTC, Ji-soo708 commented on src/main/java/com/thanksd/server/service/DiaryService.java
> +                .collect(Collectors.toList());
아 맞습니다. 해당 기능은 단순히 달력에 일기가 존재하는 날짜를 표시하는 API로 제작했어요. 그래서 figma에 해당 사진에 표시를 한 api가 필요한 데 여기서 다이어리 id와 사진을 같이 반환해야 해서 이 부분은 따로 API를 추가하는 게 좋을 거 같습니다! 그래서 노션에도 추가해뒀는데 이 기능은 아마 영준님이 사진 처리 로직 다 추가하실 때쯤에 제가 할 거 같아요!

2023-10-29 12:43 UTC, Ji-soo708 commented on src/main/java/com/thanksd/server/service/DiaryService.java
> +                .collect(Collectors.toList());
스트림 부분은 따로 메서드로 빼겠습니다~

2023-10-29 12:56 UTC, 0703kyj commented on src/test/java/com/thanksd/server/service/DiaryServiceTest.java
> +    }
https://thalals.tistory.com/399

이 곳에 시간관련 테스트 작성 예시가 잘 설명되어 있는 것 같아요! 참고하면 좋을 것 같습니다 :)

2023-10-29 13:59 UTC, Ji-soo708 commented on src/test/java/com/thanksd/server/service/DiaryServiceTest.java
> +    }
감사합니다! 모킹해보는 것도 좋을 거 같네요👍

2023-10-30 09:28 UTC, Ji-soo708 commented on src/test/java/com/thanksd/server/service/DiaryServiceTest.java
> +    }
제가 해당 링크에 있는 방법으로 특정 날짜로 createdTime을 조작하려 시도했는데 테스트가 실패해서 로그 찍어보니 현재 날짜(2023-10-30)로 찍힙니다. 찾아보니 저희는 Diary 엔티티에서 createdTime을 설정하고 있는 게 아니라 BaseTime을 상속해서 createdTime을 자동으로 설정하고 있는데 그래서인지 조작된 날짜로 필드가 설정안되는 거 같아요. 

이런 경우에 시간을 어떻게 조작해야 하는지 물어보는 글이 있는데 답변에는 Diary 엔티티에 `createdTime`을 저장하는 필드를 하나 더 추가하는 방식이 제일 좋을 거 같다는데(https://www.inflearn.com/questions/964768/baseentity-조작이-필요할-때-테스트-코드-작성-방법) 실제 서비스에는 필요없는 필드를 테스트때문에 하나 더 추가할 필요는 없다고 생각합니다. 그래서 차라리 날짜를 통해 조회하는 테스트는 생략하고 실제 api 호출을 통해 테스트해보는 거 어떻게 생각하시나요?

2023-10-30 09:41 UTC, 0703kyj commented on src/test/java/com/thanksd/server/service/DiaryServiceTest.java
> +    }
네 api로 테스트했을 때 문제 없다면 괜찮을 것 같습니다!

2023-10-30 09:49 UTC, Ji-soo708 reviewed
해당 달에 존재하는 일기가 없는 경우 빈 리스트를 반환하는 테스트 코드는 저희 의도와 맞다고 생각을 해서 삭제하지 않았습니다! 다시 확인해주시면 감사합니다~

2023-10-30 14:32 UTC, 0703kyj approved these changes
고생하셨습니다!! 바로 머지하면 될 것 같아요!

2023-10-30 15:06 UTC, merged