feat: 일기 삭제 시, s3에 업로드 되어 있는 이미지도 같이 삭제 기능 추가
Konkuk-ThanksD/Server pull request #14
Opened 2023-11-01 04:17 UTC by 0703kyj

## 개요
- 이전 pr에서 기능적인 부분은 완성했지만 test코드가 제대로 수행되지 않아서 s3에서 이미지 지우는 메서드 호출 부분을 controller로 바꾸고 test는 diary객체 자체에 대해서만 테스트를 진행했습니다.

## 작업사항
- s3에 업로드 된 이미지 삭제 기능 추가
- 일기 삭제 요청 시, s3에도 이미지 삭제 요청하도록 작

## 주의사항
- deleteByPath 메서드의 파라미터를 path자체를 전달하는 것에서 일기의 id를 전달해 메서드 내부에서 path를 찾도록 변경했습니다.
- Service에서 Controller로 호출 시점을 변경하여 test엔 문제 없도록 작성했습니다.

2023-11-01 13:14 UTC, Ji-soo708 requested changes
확인했습니다! 수고하셨어요. 👍 지금 PR에서는 일기 삭제하는 경우에만 S3 버킷에서 이미지 삭제 기능을 수행하고 있는데 이미지 수정에 대해서도 이전 이미지를 삭제하는 로직을 추가하는 게 좋지 않을까 싶어서 코멘트 남깁니다~

2023-11-01 13:14 UTC, Ji-soo708 commented on src/main/java/com/thanksd/server/controller/DiaryController.java
> +        presignedUrlService.deleteByPath(id);
이 부분이 서비스로 옮겨가는 게 제일 베스트이긴 한데 지금 당장 고칠 수 없다면 나중에 리팩토링하는 게 좋을 거 같아요! 그리고 `private final String prefixImagePath = "images";` 이 부분 PreSignedUrlService 단으로 옮길 수 있을까요?

2023-11-02 01:58 UTC, 0703kyj commented on src/main/java/com/thanksd/server/controller/DiaryController.java
> +        presignedUrlService.deleteByPath(id);
원래는 서비스단에서 호출했었는데 테스트할때, 처리하기가 곤란해서 일단 빼놨습니다..ㅠㅠ 매번 s3에 삭제 요청을 해야하는데 없는 경우 에러가 나더라고요..ㅠ 나중에 방법을 찾던지 아니면 해당 test만 무시하고 진행하게 하던지 해야될 것 같네요! 수정에 대해서는 따로 브랜치 파서 작업하려 했는데 볼륨이 크지 않아 같이 하고 머지해도 될 것 같아요! 추가해서 커밋하겟습니다~

2023-11-02 01:58 UTC, 0703kyj commented on src/main/java/com/thanksd/server/controller/DiaryController.java
> +        presignedUrlService.deleteByPath(id);
prefix부분은 PreSignedUrlService 단으로 옮겨놓을게요!

2023-11-02 04:35 UTC, 0703kyj commented
수정 시에도 기존 이미지 삭제 로직 추가했습니다! 다만 이 부분도 controller단에 있어서 추후 리펙토링하겠습니다~~

2023-11-03 12:37 UTC, Ji-soo708 approved these changes
확인했습니다! 기능 상으로는 문제 없어보여 approve 할게요! 수고하셨습니다~

2023-11-06 00:04 UTC, merged