feat: 오늘 날짜가 포함된 주에 작성한 일기 개수를 반환하는 기능 추가
Konkuk-ThanksD/Server pull request #23
Opened 2023-11-19 11:52 UTC by 0703kyj

## 개요
- 주별 일기 작성 개수 반환하는 기능을 추가했습니다.

## 작업사항
- 주어진 날짜가 포함된 주에 작성한 일기 개수를 반환하는 기능 추가
  - 날짜는 query를 통해 받도록 했습니다.
- 관련 테스트 코드 작성

## 주의사항
- BaseTime관련 테스트 코드를 작성해야 해서 일부 경우에 대해서만 테스트 진행했습니다.

2023-11-20 08:55 UTC, Ji-soo708 requested changes
기능 동작 확인했습니다. 수고하셨어요~ 코드 보면서 개선할 수 있는 부분에 대해 코멘트 남겼어요!

2023-11-20 08:55 UTC, Ji-soo708 commented on src/main/java/com/thanksd/server/controller/DiaryController.java
> +        DiaryWeekCountResponse response = diaryService.findDiaryCountByWeek(memberId,LocalDate.of(year,month,day));
파람으로 받은 year, month, day를 LocalDate화시키는 코드를 서비스로 옮기는 게 가독성이 더 좋을 거 같아요! 아니면 `해당 날짜에 존재하는 일기 조회`처럼 `@RequestParam("date") @DateTimeFormat(pattern = "yyyy-MM-dd") LocalDate date`로 파람을 받아도 좋을 거 같아요~

2023-11-20 08:55 UTC, Ji-soo708 commented on src/main/java/com/thanksd/server/service/DiaryService.java
> +    public DiaryWeekCountResponse findDiaryCountByWeek(Long memberId, LocalDate today) {
유효하지 않은 날짜(ex. 2023-02-31)를 인자로 넘겨주면 500 에러가 떠요. 프론트에서 잘못된 날짜를 넘길 확률은 매우 적지만 #15 처럼 예외처리하면 좋을 거 같아요. 👍

2023-11-21 04:06 UTC, 0703kyj commented on src/main/java/com/thanksd/server/service/DiaryService.java
> +    public DiaryWeekCountResponse findDiaryCountByWeek(Long memberId, LocalDate today) {
그러네요! 예외처리 해서 올리겠습니다~~

2023-11-21 04:37 UTC, 0703kyj commented on src/main/java/com/thanksd/server/controller/DiaryController.java
> +        DiaryWeekCountResponse response = diaryService.findDiaryCountByWeek(memberId,LocalDate.of(year,month,day));
@RequestParam("date") @DateTimeFormat(pattern = "yyyy-MM-dd") LocalDate date
-> 좋은 방법인 것 같아서 이걸로 수정했습니다! 예외처리까지 한번에 되네요 :)

2023-11-21 09:18 UTC, Ji-soo708 approved these changes
확인했습니다. 수고하셨어요~

2023-11-22 05:56 UTC, merged