feat: 일기 기본 CRUD 작성
Konkuk-ThanksD/Server pull request #7
Opened 2023-10-25 05:58 UTC by 0703kyj

## 개요
- 일기 기본 CRUD를 작성했습니다
- 관련 로직은 전부 서비스 단에서 작성했습니다.  
  - 일기 Create
    - path에 제공된 member-id를 통해 맴버 찾기 -> 저장
  - 일기 Update
    - path에 제공된 diary-id를 통해 일기 찾기 -> Setter를 통해 값 수정 -> repository save메서드 통해 다시 저장
    - 추후 Setter 제거하고 수정 예정
  - 일기 Delete
    - path에 제공된 diary-id를 통해 일기 찾기 -> 있으면 삭제
    - 일기가 없다면 예외 처리

## 작업사항
- Diary 및 Member 연관관계 매핑
- Diary 서비스 로직 작성
- DiaryService 테스트 코드 작성
- DiaryController 작성

## 주의사항
- update 쿼리가 제대로 실행이 안돼서 임시로 Diary의 Setter를 열어놨습니다. 추후 수정하겠습니다.
- postman을 통해 api테스트 진행했습니다. 제가 해봤을 땐 이상없었는데 한 번 확인 부탁드립니다.
- 몇가지 api 추가 작성 및 변경이 있습니다. notion 명세서 확인 바랍니다.
- 초반 커밋에서 테스트 코드 작성 부분이 feat으로 되어 있습니다... 좀 더 신경 써서 작성하겠습니다.
- 처리가 안된 사항이나 부족한 부분은 바로 말씀주세요..!!!

2023-10-26 04:23 UTC, Ji-soo708 requested changes
CRUD 다 구현하느라 정말 수고하셨습니다! 다만 기능별로 브랜치를 나누는 게 코드 리뷰하기에 편해서 다음부터는 그렇게 부탁드릴게요~ (ex. feat/create-diary, feat/update-diary)

일단 코드를 찬찬히 봤는데 다이어리 생성에서 프론트에서 이미지 데이터를 받아서 어떻게 S3에 저장할 건지에 대한 로직이 없는 거 같아 일단은 다이어리 생성 기능에 대해서만 코드 리뷰 남겼습니다. 이 부분 어떻게 처리하실 예정이신지 알려주시면 감사합니다. 🙂 
(코드리뷰에도 적었지만 S3를 사용한다면 크게 multipart/form-data, presigned url 두가지 방식 중 하나로 많이 처리하는데 어떤 방식을 처리하냐에 따라 프론트에서도 처리하는 로직이 달라질 수 있어서 서로 협의하고 정하는 게 좋을 거 같습니다~)

2023-10-26 04:23 UTC, Ji-soo708 commented on src/main/java/com/thanksd/server/domain/Diary.java
> +    }
줄 한칸 띄우는 게 가독성 조금 더 나아질 거 같습니다!

2023-10-26 04:23 UTC, Ji-soo708 commented on src/main/java/com/thanksd/server/controller/DiaryController.java
> +
이 줄 없애주시고 어노테이션을 `public Response<Object> saveDiary` 위에 바로 붙여주세요.

2023-10-26 04:23 UTC, Ji-soo708 commented on src/main/java/com/thanksd/server/service/MemberService.java
> +                .orElseThrow(() -> new NotFoundMemberException());
```suggestion
                .orElseThrow(NotFoundMemberException::new);
```


코드 보면 `Lambda can be replaced with method reference` 이게 뜨는데 예외 던지는 코드를 이렇게 바꿀 수 있을 거 같아요!

2023-10-26 04:23 UTC, Ji-soo708 commented on src/main/java/com/thanksd/server/repository/DiaryRepository.java
> +//    @Modifying
안쓰는 메서드는 삭제해주세요

2023-10-26 04:23 UTC, Ji-soo708 commented on src/main/java/com/thanksd/server/service/DiaryService.java
> +                .orElseThrow(() -> new NotFoundMemberException());
이 부분에서 지금 `Lambda can be replaced with method reference`뜨는데
```suggestion
               .orElseThrow(NotFoundMemberException::new);
```

이렇게 개선할 수 있는데 어떠신가요??

2023-10-26 04:23 UTC, Ji-soo708 commented on src/main/java/com/thanksd/server/dto/response/diary/DiaryAllResponse.java
> +}
빨간 색 정지 표시가 뜨는데 클래스 마지막 줄은 엔터 한 번 더 눌러서 파일 끝에 개행문자(\n)를 넣어야 합니다. (EOF문제) 안그러면 머지할 때 conflict가 발생할 수도 있어요~

2023-10-26 04:23 UTC, Ji-soo708 commented on src/main/java/com/thanksd/server/service/MemberService.java
> +    public DiaryIdResponse deleteDiary(Long memberId, Long diaryId) {
deleteDiary를 MemberService에 잘못 추가하신 거 같아요. 삭제 부탁드립니다~

2023-10-26 04:23 UTC, Ji-soo708 commented on src/test/java/com/thanksd/server/service/DiaryServiceTest.java
> +    public void saveDiary() throws Exception {
현재 예외가 발생하지 않아서 `Exception 'java.lang.Exception' is never thrown in the method ` 이게 뜨는데 throws Exception을 추가하신 이유가 있으실까요?

2023-10-26 04:23 UTC, Ji-soo708 commented on src/test/java/com/thanksd/server/service/DiaryServiceTest.java
> +
필요없는 줄바꿈은 삭제하는 게 좋을 거 같습니다!

2023-10-26 04:23 UTC, Ji-soo708 commented on src/test/java/com/thanksd/server/service/DiaryServiceTest.java
> +}
이 부분도 EOF 문제가 있습니다.

2023-10-26 04:23 UTC, Ji-soo708 commented on src/main/java/com/thanksd/server/service/DiaryService.java
> +        Diary diary = diaryRepository.save(
현재 프론트에게서 받은 이미지 데이터를 서버에 저장하는 로직이 없는 거 같습니다. (ex. S3)
혹시 어떻게 처리할 생각이신가요? 일반적으로는 multipart/form-data 형식으로 받아서 혹은 presigned url 을 통해 S3 버킷에 올립니다.

2023-10-26 04:25 UTC, Ji-soo708 commented on src/test/java/com/thanksd/server/service/DiaryServiceTest.java
> +@Transactional
`DatabaseCleaner` 를 통해 모든 작업은 단일 트랜잭션 내에서 실행되도록 처리해서 `@Transactional` 안 붙여도 됩니다~

2023-10-26 04:34 UTC, Ji-soo708 commented on src/main/java/com/thanksd/server/dto/response/diary/DiaryAllResponse.java
> +package com.thanksd.server.dto.response.diary;
request의 경우 바로 추가하셨는데 response는 도메인별로 패키지 하나 파셔서 거기에 추가하셨더라고요. 저는 dto.request or dto.response 내에서는 도메인별로 한 번 더 나눌 필요가 없다 생각해서 영준님이 request에 하신 거처럼 바로 추가했는데 어떤 방식이 더 나으실 거 같나요?
형식을 통일하는 게 좋을 거 같아 코멘트 남깁니다~

2023-10-26 06:31 UTC, 0703kyj commented on src/test/java/com/thanksd/server/service/DiaryServiceTest.java
> +    public void saveDiary() throws Exception {
템플릿 만들어서 쓰다보니까 자동으로 들어갔네요.. 삭제할게요!

2023-10-26 06:33 UTC, 0703kyj commented on src/main/java/com/thanksd/server/dto/response/diary/DiaryAllResponse.java
> +package com.thanksd.server.dto.response.diary;
도메인별로 안나누고 바로 추가할게요! 다시 생각해보니 굳이 나눌 필요는 없을 것 같네요!

2023-10-26 06:51 UTC, 0703kyj commented on src/main/java/com/thanksd/server/service/DiaryService.java
> +        Diary diary = diaryRepository.save(
해당 로직은 아직 관련 공부가 미흡해서 추후에 추가할 계획이였습니다..!
조언해주신 내용 토대로 프런트분들이랑 상의해보고 결정해서 추가하도록 하겠습니다~

2023-10-27 03:33 UTC, Ji-soo708 requested changes
수정 부분 다 확인했고 일기 수정, 삭제, 조회 쪽에 대해서도 쭉 봤습니다! 수고하셨어요~ 아직 변경해야 할 부분이 좀 남아있어서 RC 날립니다. 아마 새로 코멘트 남긴 것들만 해결되면 머지가 될 거 같아요. 사진 업로드 처리 로직은 따로 브랜치 파셔서 추가하실 예정이시죠?

2023-10-27 03:33 UTC, Ji-soo708 commented on src/main/java/com/thanksd/server/controller/DiaryController.java
> +    public Response<Object> findAllDairy(@PathVariable("id") Long memberId){
지금에서야 알아챘는데 `@PathVariable("id")` 가 아니라 `@LoginUserId` 를 넣어야 자동으로 인증 수행합니다. 이에 대한 설명은 아래 PR 주의사항에 적어놨어요! https://github.com/Konkuk-ThanksD/Server/pull/3

아래는 다른 프로젝트 댓글 등록 기능인데 이거 참고해서 어노테이션 수정하시면 됩니다.
<img width="644" alt="image" src="https://github.com/Konkuk-ThanksD/Server/assets/69844138/a8a45d6d-c0f5-4172-b6af-00792c62dee7">
그리고 저희가 JWT로 인증을 수행하고 있어서 로그인이 필요한 서비스들은 `@SecurityRequirement(name = "JWT")` 도 사진처럼 달아주세요!

2023-10-27 03:33 UTC, Ji-soo708 commented on src/main/java/com/thanksd/server/service/DiaryService.java
> +        findDiary.setContent(validateData(findDiary.getContent(), diaryRequest.getContent()));
세터는 지양하는 게 좋아서 해당 엔티티 클래스에서 `@Setter` 지우고 엔티티 내에서 업데이트용 메서드 하나 만들어 호출해서 쓰는 게 더 객체지향스러울 거 같아요!

2023-10-27 03:33 UTC, Ji-soo708 commented on src/main/java/com/thanksd/server/service/DiaryService.java
> +    public DiaryIdResponse saveDiary(DiaryRequest diaryRequest, Long memberId) {
일기를 작성할 때
`{
  "content": "",
  "font": "",
  "image": ""
}` 이렇게 요청을 보내도 200이 뜹니다. 제가 볼 때는 서버에서도 이미지, 콘텐츠, 폰트에 대해 공백을 보내면 예외처리 해주는 게 좋을 거 같아요.

2023-10-27 03:33 UTC, Ji-soo708 commented on src/main/java/com/thanksd/server/controller/DiaryController.java
> +    @GetMapping("/member/{id}")
바로 아래에도 코멘트 달았지만 그래서 uri에 {id}를 넣을 필요가 없습니다! 깔끔하게 `@GetMapping` 이렇게 수정하시면 될 거 같아요~

2023-10-27 03:33 UTC, Ji-soo708 commented on src/main/java/com/thanksd/server/controller/DiaryController.java
> +    @GetMapping("/member/{id}")
<img width="514" alt="image" src="https://github.com/Konkuk-ThanksD/Server/assets/69844138/ab2386b6-bb4b-481a-bd0e-7a91a646d517">
그리고 프론트 편의성을 위해 배포 후, 스웨거 api docs도 드리려고 스웨거 설정해놔서 사진처럼 각 기능별로 `@Operation` 달아주면 좋을 거 같습니다. 
<img width="1504" alt="image" src="https://github.com/Konkuk-ThanksD/Server/assets/69844138/67a8021d-9761-48de-adb1-0f9cb5475943">
그래야 스웨거에 이렇게 뜹니다! 그리고 서버 실행 후 localhost:8080/swagger-ui/index.html 여기로 들어가서 스웨거로 api 테스트 하시면 더 편리할 수 있습니다!

2023-10-27 03:33 UTC, Ji-soo708 commented on src/main/java/com/thanksd/server/controller/DiaryController.java
> +    @PostMapping("/member/{id}")
이것도 마찬가지로 그냥 @PostMapping으로 끝내도 됩니다!

2023-10-27 04:14 UTC, 0703kyj commented on src/main/java/com/thanksd/server/controller/DiaryController.java
> +    public Response<Object> findAllDairy(@PathVariable("id") Long memberId){
그렇군요! 수정하겠습니다!!

2023-10-27 04:15 UTC, 0703kyj commented on src/main/java/com/thanksd/server/service/DiaryService.java
> +        findDiary.setContent(validateData(findDiary.getContent(), diaryRequest.getContent()));
넵 이것도 수정해서 반영해 놓을게요!

2023-10-27 04:18 UTC, 0703kyj commented on src/main/java/com/thanksd/server/controller/DiaryController.java
> +    @PostMapping("/member/{id}")
저는 맴버 아이디를 받아와서 처리해줘야 된다고 생각했는데 혹시 현재 맴버를 받아올 수 있는 방법이 따로 있는 건가요?

2023-10-27 04:19 UTC, 0703kyj commented on src/main/java/com/thanksd/server/controller/DiaryController.java
> +    @GetMapping("/member/{id}")
네 추가할게요! 정말 많이 배우고 있는 느낌이네요. 감사합니다~~

2023-10-27 04:53 UTC, Ji-soo708 commented on src/main/java/com/thanksd/server/controller/DiaryController.java
> +    @PostMapping("/member/{id}")
제가 로그인 처리 로직 추가할 때 HandlerInterCeptor와 HandlerMethodArgumentResolver를 이용하여 @LogInId 어노테이션이 있는 파라미터 변수가 있다면 조기에 jwt을 분석하고 값을 할당하도록 했습니다. 그러면 로그인 할 때 주는 액세스 토큰을 프론트에서 api 요청할 때마다 헤더에 담아서 줄텐데 그러면 해당 토큰을 가지고 로그인한 멤버를 인식합니다. 그래서 `"/member/{id}"` 따로 이렇게 인자 안넣어도 로그인한 멤버를 알아서 인식해줍니다.
<br>

<img width="659" alt="image" src="https://github.com/Konkuk-ThanksD/Server/assets/69844138/cff2f7d8-466e-417b-bf22-cf20347b2c33">
이 얘기를 하니까 생각난건데 현재 로그인은 인터셉터 기반 로그인으로 구현되어 있어서 일기 관련 기능도 인터셉터에서 요청을 처리하기 전에 먼저 가로채서 인증을 수행해야 합니다. 그래서 아래 사진은 AuthConfig 클래스인데 여기서 `.addPathPatterns("/members/**")` 이 부분을 `.addPathPatterns("/members/**", "/diaries/**")` 이렇게 경로를 추가해줘야 다이어리 기능에서도 인증 로직이 자동으로 수행됩니다!
참고로 `.excludePathPatterns`는 로그인 없이도 이용 가능한 uri를 추가하는 기능입니다!

2023-10-27 05:45 UTC, 0703kyj commented on src/main/java/com/thanksd/server/controller/DiaryController.java
> +    @PostMapping("/member/{id}")
아 이해했습니다! 자세히 설명해주셔서 감사합니다!! 😄

2023-10-29 06:15 UTC, Ji-soo708 commented
수정사항 잘 반영된 거 확인했습니다! 수고 많으셨어요. 👍
제가 api 직접 호출하면서 확인해보니까 **일기 수정/삭제/조회 기능**에서 id값만 주어지면 다른 사람들의 일기도 수정/삭제/조회가 가능하더라고요. 저희 서비스에서는 남들의 일기는 수정/삭제/조회 할 수 없도록 해야하니 이 부분까지 꼼꼼하게 예외처리 해주시면 완벽할 거 같아요.
기능은 일단 다 되니까 approve하겠습니다. 위에 남긴 부분만 확인해주세요~

2023-10-29 06:16 UTC, Ji-soo708 approved these changes
수정사항 잘 반영된 거 확인했습니다! 수고 많으셨어요. 👍
제가 api 직접 호출하면서 확인해보니까 **일기 수정/삭제/조회 기능**에서 id값만 주어지면 다른 사람들의 일기도 수정/삭제/조회가 가능하더라고요. 저희 서비스에서는 남들의 일기는 수정/삭제/조회 할 수 없도록 해야하니 이 부분까지 꼼꼼하게 예외처리 해주시면 완벽할 거 같아요.
기능은 일단 다 되니까 approve하겠습니다. 위에 남긴 부분만 확인하셔서 수정하고 바로 머지하시면 될 거 같습니다!

2023-10-29 07:19 UTC, 0703kyj commented
아 그 부분을 고려안했던건 아닌데 프런트 쪽에서 다른 사람의 일기는 애초에 접근할 수 없다고 생각해서 처리 안했었습니다..! 다시 생각해보니 확인 한 번 해주는게 좋을 것 같네요! 수정해서 머지할게요~

2023-10-29 08:14 UTC, merged